// AUTO-GENERATED by scripts/generate_protocol_ts.py from app.ipc_schema.
// Do not edit this file directly.

export interface JsonRpcError {
  code: number;
  message: string;
}

export interface JsonRpcRequest {
  jsonrpc: "2.0";
  id: number;
  method: string;
  params?: unknown;
}

export interface JsonRpcNotification {
  jsonrpc: "2.0";
  method: string;
  params?: unknown;
}

export interface JsonRpcResponse {
  jsonrpc: "2.0";
  id: number;
  result?: unknown;
  error?: JsonRpcError;
}

export interface AttachmentMeta {
  path: string;
  lines: number;
  chars: number;
}

export interface AttachmentReference {
  path: string;
}

export interface ConstructRef {
  kind: string;
  query: string;
  token?: string;
  id?: string;
  label?: string;
}

export interface ChatRequestParams {
  message: string;
  model?: string;
  attachments?: AttachmentMeta[];
  construct_refs?: ConstructRef[];
}

export interface CommandRequestParams {
  cmd: string;
  args: string[];
}

export interface CompleteRequestParams {
  prefix?: string;
  suffix?: string;
  prompt?: string;
  model?: string;
  max_tokens?: number;
  temperature?: number;
  stop?: string[];
}

export interface RouteListRequestParams {
  includeHidden?: boolean;
}

export interface RouteSelectRequestParams {
  route: string;
  requestId?: string;
  probeAfterSelect?: boolean;
}

export interface RouteStatusRequestParams {
  route?: string;
}

export interface RouteProbeRequestParams {
  route?: string;
  prompt?: string;
  timeoutMs?: number;
}

export interface InventoryQueryRequestParams {
  routeNames?: string[];
  route?: string;
  forceRefresh?: boolean;
}

export interface InventoryResolveRequestParams {
  alias?: string;
  model?: string;
  autoLoad?: boolean;
}

export interface InventoryResolveResponseParams {
  alias: string;
  canonical_name: string;
  model_id: string;
  backend: string;
  api_base: string;
}

export interface CompleteResponseParams {
  text: string;
  finish_reason?: string;
  prompt_tokens?: number;
  completion_tokens?: number;
  model?: string;
}

export interface TextParams {
  delta: string;
  request_id?: string;
  span_id?: string;
}

export interface ToolCallParams {
  name: string;
  server: string;
  arguments: string;
  call_id?: string;
  tool_group?: string;
  request_id?: string;
  span_id?: string;
}

export interface ToolResultParams {
  name: string;
  result: string;
  server?: string;
  call_id?: string;
  tool_group?: string;
  request_id?: string;
  span_id?: string;
}

export interface ThinkingParams {
  delta: string;
  request_id?: string;
  span_id?: string;
}

export interface ErrorParams {
  message: string;
  request_id?: string;
  span_id?: string;
}

export interface MessageParams {
  id: string;
  role: "user" | "assistant" | "system" | "tool";
  content: string;
  timestamp: number;
  thinking?: string | null;
  turn_id?: string | null;
  model?: string | null;
  tool_name?: string | null;
  tool_server?: string | null;
  tool_arguments?: string | null;
  tool_group?: string | null;
  attachments?: AttachmentMeta[] | null;
  construct_refs?: ConstructRef[] | null;
  request_id?: string | null;
  span_id?: string | null;
}

export interface DoneParams {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  request_id?: string;
  end_status?: string;
}

export interface ReadyModelInfo {
  name: string;
  model_id: string;
  role: string;
  description?: string;
  loaded: boolean;
  selectable?: boolean;
  tools_enabled: boolean;
  provider?: string;
  context_budget?: number;
  loaded_identifier?: string;
  size_bytes?: number;
  status?: string;
  parallel?: number;
  context_length?: number;
  max_context_length?: number;
  architecture?: string;
  quantization?: string;
  queued?: number;
  estimated_gpu_bytes?: number;
  estimated_total_bytes?: number;
}

export interface LoadedModelRuntimeInfo {
  identifier: string;
  model_key: string;
  display_name?: string;
  size_bytes?: number;
  architecture?: string;
  quantization?: string;
  context_length?: number;
  max_context_length?: number;
  parallel?: number;
  status?: string;
  queued?: number;
  ttl_ms?: number;
  estimated_gpu_bytes?: number;
  estimated_total_bytes?: number;
}

export interface ReadyParams {
  version: string;
  backend: string;
  active_model: string;
  mode: string;
  workspace: string;
  rom_path: string;
  tools_enabled: boolean;
  servers: string[];
  tool_count: number;
  warnings: string[];
  models: ReadyModelInfo[];
  model_catalog?: ReadyModelInfo[];
  session_path: string;
  loaded_models?: LoadedModelRuntimeInfo[];
  loaded_model_count?: number;
  loaded_model_memory_bytes?: number;
  studio_model?: string;
  studio_api_base?: string;
  studio_node?: string;
  llamacpp_api_base?: string;
  llamacpp_model?: string;
  llamacpp_node?: string;
  tools_write?: boolean;
  verify_hooks?: boolean;
  focus_file?: string;
  lsp_context_mode?: string;
  registry_path?: string;
  broadcast_models?: string[];
  orchestrator_model?: string;
  prompt_tokens?: number;
  completion_tokens?: number;
  cache_creation_tokens?: number;
  cache_read_tokens?: number;
  session_messages?: number;
  session_tool_calls?: number;
  last_active_at?: string;
  last_active_model?: string;
  permission_rules?: Record<string, boolean>;
  shell_active?: boolean;
  shell_cwd?: string;
  cancel_count?: number;
  backend_restart_count?: number;
  tool_latency_ms?: number;
  tool_latency_samples?: number;
  review_wait_ms?: number;
  permission_wait_ms?: number;
  permission_timeout_count?: number;
  review_timeout_count?: number;
  model_retry_count?: number;
  model_retry_backoff_ms?: number;
  model_error_count?: number;
  tool_timeout_count?: number;
  model_backpressure_count?: number;
  tool_backpressure_count?: number;
  model_queue_highwater?: number;
  tool_queue_highwater?: number;
  model_inflight_highwater?: number;
  tool_inflight_highwater?: number;
  inflight_model_calls?: number;
  queued_model_calls?: number;
  inflight_tool_calls?: number;
  queued_tool_calls?: number;
  model_retry_max?: number;
  model_retry_base_ms?: number;
  tool_exec_timeout_s?: number;
  max_inflight_model_calls?: number;
  max_inflight_tools?: number;
  exec_queue_depth?: number;
  request_count?: number;
  request_success_count?: number;
  request_error_count?: number;
  request_reject_count?: number;
  request_cancel_count?: number;
  model_alias_resolutions?: number;
  model_lookup_failures?: number;
  model_request_counts?: Record<string, number>;
  span_count?: number;
  last_request_id?: string;
  last_span_id?: string;
  last_tool_call_id?: string;
  request_samples?: number;
  queued_ms_p50?: number;
  queued_ms_p95?: number;
  model_ms_p50?: number;
  model_ms_p95?: number;
  tool_ms_p50?: number;
  tool_ms_p95?: number;
  total_ms_p50?: number;
  total_ms_p95?: number;
  last_request_status?: string;
  last_request_queued_ms?: number;
  last_request_model_ms?: number;
  last_request_tool_ms?: number;
  last_request_total_ms?: number;
}

export interface UiEventParams {
  kind: string;
  requestId?: string;
  routeName?: string;
  message?: string;
  health?: string;
  observedAt?: string;
  route?: Record<string, object>;
  routeStatus?: Record<string, object>;
  inventory?: Record<string, object>;
}

export interface ToolPermissionRequestParams {
  name: string;
  server: string;
  arguments: string;
  reason?: string;
}

export interface ToolReviewRequestParams {
  review_id: string;
  name: string;
  server: string;
  summary: string;
  paths: string[];
  diff_lines: string[];
  omitted: number;
  verification_commands?: string[];
}

export interface ContextCompactedParams {
  summary: string;
  replaced: number;
  tokens_before: number;
  tokens_after: number;
  model: string;
}

export interface SubagentStartParams {
  id: string;
  name: string;
  model: string;
  provider: string;
  depth: number;
  parent_id?: string | null;
}

export interface SubagentTextParams {
  id: string;
  delta: string;
}

export interface SubagentThinkingParams {
  id: string;
  delta: string;
}

export interface SubagentToolCallParams {
  id: string;
  name: string;
  server: string;
  arguments: string;
  call_id: string;
}

export interface SubagentToolResultParams {
  id: string;
  name: string;
  result: string;
  call_id: string;
}

export interface SubagentDoneParams {
  id: string;
  name: string;
  model: string;
  text: string;
  prompt_tokens: number;
  completion_tokens: number;
  tool_calls: number;
  error?: string;
  cancelled?: boolean;
}

export interface SubagentErrorParams {
  id: string;
  message: string;
}

// Request wrappers

export type ChatRequest = JsonRpcRequest & {
  method: "chat";
  params: ChatRequestParams;
};

export type CommandRequest = JsonRpcRequest & {
  method: "command";
  params: CommandRequestParams;
};

export type CompleteRequest = JsonRpcRequest & {
  method: "complete";
  params: CompleteRequestParams;
};

export type StatusRequest = JsonRpcRequest & {
  method: "status";
};

export type ModelsRequest = JsonRpcRequest & {
  method: "models";
};

export type RouteListRequest = JsonRpcRequest & {
  method: "route/list";
  params: RouteListRequestParams;
};

export type RouteSelectRequest = JsonRpcRequest & {
  method: "route/select";
  params: RouteSelectRequestParams;
};

export type RouteStatusRequest = JsonRpcRequest & {
  method: "route/status";
  params: RouteStatusRequestParams;
};

export type RouteProbeRequest = JsonRpcRequest & {
  method: "route/probe";
  params: RouteProbeRequestParams;
};

export type InventoryQueryRequest = JsonRpcRequest & {
  method: "inventory/query";
  params: InventoryQueryRequestParams;
};

export type InventorySnapshotRequest = JsonRpcRequest & {
  method: "inventory/snapshot";
  params: InventoryQueryRequestParams;
};

export type InventoryRefreshRequest = JsonRpcRequest & {
  method: "inventory/refresh";
  params: InventoryQueryRequestParams;
};

export type InventoryResolveRequest = JsonRpcRequest & {
  method: "inventory/resolve";
  params: InventoryResolveRequestParams;
};

// Notification wrappers

export interface TextNotification extends JsonRpcNotification {
  method: "text";
  params: TextParams;
}

export interface ToolCallNotification extends JsonRpcNotification {
  method: "tool_call";
  params: ToolCallParams;
}

export interface ToolResultNotification extends JsonRpcNotification {
  method: "tool_result";
  params: ToolResultParams;
}

export interface MessageNotification extends JsonRpcNotification {
  method: "message";
  params: MessageParams;
}

export interface DoneNotification extends JsonRpcNotification {
  method: "done";
  params: DoneParams;
}

export interface ThinkingNotification extends JsonRpcNotification {
  method: "thinking";
  params: ThinkingParams;
}

export interface ErrorNotification extends JsonRpcNotification {
  method: "error";
  params: ErrorParams;
}

export interface ReadyNotification extends JsonRpcNotification {
  method: "ready";
  params: ReadyParams;
}

export interface ToolPermissionNotification extends JsonRpcNotification {
  method: "tool/permission_request";
  params: ToolPermissionRequestParams;
}

export interface ContextCompactedNotification extends JsonRpcNotification {
  method: "context/compacted";
  params: ContextCompactedParams;
}

export interface ToolReviewNotification extends JsonRpcNotification {
  method: "tool/review_request";
  params: ToolReviewRequestParams;
}

export interface SubagentStartNotification extends JsonRpcNotification {
  method: "subagent/start";
  params: SubagentStartParams;
}

export interface SubagentTextNotification extends JsonRpcNotification {
  method: "subagent/text";
  params: SubagentTextParams;
}

export interface SubagentThinkingNotification extends JsonRpcNotification {
  method: "subagent/thinking";
  params: SubagentThinkingParams;
}

export interface SubagentToolCallNotification extends JsonRpcNotification {
  method: "subagent/tool_call";
  params: SubagentToolCallParams;
}

export interface SubagentToolResultNotification extends JsonRpcNotification {
  method: "subagent/tool_result";
  params: SubagentToolResultParams;
}

export interface SubagentDoneNotification extends JsonRpcNotification {
  method: "subagent/done";
  params: SubagentDoneParams;
}

export interface SubagentErrorNotification extends JsonRpcNotification {
  method: "subagent/error";
  params: SubagentErrorParams;
}

export interface UiEventNotification extends JsonRpcNotification {
  method: "ui/event";
  params: UiEventParams;
}

export type BackendEvent =
  TextNotification
  | ToolCallNotification
  | ToolResultNotification
  | MessageNotification
  | DoneNotification
  | ThinkingNotification
  | ErrorNotification
  | ReadyNotification
  | ToolPermissionNotification
  | ContextCompactedNotification
  | ToolReviewNotification
  | SubagentStartNotification
  | SubagentTextNotification
  | SubagentThinkingNotification
  | SubagentToolCallNotification
  | SubagentToolResultNotification
  | SubagentDoneNotification
  | SubagentErrorNotification
  | UiEventNotification
;
